version: '3.6'
services:
  web:
    image: odoo:12.0
    depends_on:
      - db
    ports:
      - "8069:8069"
    deploy: 
      placement: 
        constraints:
          - node.labels.node_number==3
  db:
    image: postgres:10
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
    deploy: 
      placement: 
        constraints:
          - node.labels.node_number==3
          
  